version: "2.7"

services:
  medical_db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=medical_postgres_password
      - POSTGRES_DB=medical
    expose:
      - "5432"

  queue:
    image: rabbitmq:3

  backend:
    depends_on:
      - medical_db
    links:
      - medical_db
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    expose:
      - "8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=medical_postgres_password
      - POSTGRES_SERVER=medical_db
      - POSTGRES_DB=medical
    labels:
      traefik.enable: true
      traefik.http.routers.backend.entrypoints: web
      traefik.http.routers.backend.rule: Host(`api.hc-solutions.local`)

  search:
    image: getmeili/meilisearch:v0.23.1
    restart: always
    volumes:
      - meilidate:/data.ms
    environment:
      MEILI_MASTER_KEY: "qwerty"
      MEILI_NO_ANALYTICS: "true"
      MEILI_LOG_LEVEL: "WARN"
    expose:
      - "7700"
    labels:
      traefik.enable: true
      traefik.http.routers.search.entrypoints: web
      traefik.http.routers.search.rule: Host(`ms.hc-solutions.local`)

  traefik:
    image: traefik:v2.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command:
      # api
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      # general logs
      - --log.level=DEBUG
      # set providers
      - --providers.docker=true                   # docker is a provider
      # - --providers.docker.network=medical        # only look at containers this network
      - --providers.docker.exposedbydefault=false # each container needs to be explicitly enabled to be seen by traefik (- "traefik.enable=true")
      # set entrypoints
      - --entrypoints.web.address=:80
    labels:
      traefik.enable: true # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      traefik.http.routers.traefik.rule: Host(`traefik.hc-solutions.local`)
      traefik.http.services.traefik.loadbalancer.server.port: 8080

    ports:
      - "80:80"

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "3000"
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.routers.frontend.rule: Host(`hc-solutions.local`)

volumes:
  app-db-data:
  meilidate:
  keycloak_postgres:

networks:
  default:
