"""changes in diagnoses, procedures with expiration

Revision ID: 6bc47209f54e
Revises: bf7f2bbcf39e
Create Date: 2022-01-06 16:20:06.806196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bc47209f54e"
down_revision = "bf7f2bbcf39e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disease_classifiers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_actual", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "diseases", "disease_classifiers", ["source"], ["id"])
    op.drop_column("diseases", "is_actual")
    op.add_column(
        "procedures", sa.Column("expires_in_days", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("procedures", "expires_in_days")
    op.add_column(
        "diseases",
        sa.Column("is_actual", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "diseases", type_="foreignkey")
    op.drop_table("disease_classifiers")
    # ### end Alembic commands ###
