"""procedures table definition was updated

Revision ID: bf7f2bbcf39e
Revises: 9f63f4afe62b
Create Date: 2021-12-19 16:01:53.815049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7f2bbcf39e'
down_revision = '9f63f4afe62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'procedures', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='unique')
    # ### end Alembic commands ###
