"""appointment update

Revision ID: cbe3fc70a369
Revises: f2ec64268f66
Create Date: 2022-01-06 22:42:02.985107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbe3fc70a369'
down_revision = 'f2ec64268f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_appointments', 'scheduled_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_appointments', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
