"""appointment update

Revision ID: ee7527eaed8e
Revises: 6e47afba9477
Create Date: 2022-01-06 22:47:10.788976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee7527eaed8e"
down_revision = "6e47afba9477"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
