"""expiration columns was added

Revision ID: f2ec64268f66
Revises: be37f32c32ea
Create Date: 2022-01-06 19:17:19.367989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2ec64268f66"
down_revision = "be37f32c32ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "procedures_records", sa.Column("expires_at", sa.DATE(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("procedures_records", "expires_at")
    # ### end Alembic commands ###
