name: Build-push-scan

on:
  push:
    branches: ["staging"]
  pull_request_review:
    branches: ["staging"]
    types: [submitted]

jobs:
  cleanup:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    container:
      image: ghcr.io/hc-solutions/ubuntu:20.04
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Cleaning up the $GITHUB_WORKSPACE as root from a Docker image
        shell: bash
        run: if [[ -d /__w ]]; then chown -R 1000:1000 /__w; fi
  
  checkout:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    needs: [cleanup]
    outputs:
      app-name: ${{ steps.get-app-name.outputs.app-name }}
      app-version: ${{ steps.get-app-version.outputs.app-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: get-app-name
        run: echo "::set-output name=app-name::`grep 'name:' ./helm/Chart.yaml | cut -d ' ' -f 2`"
      - id: get-app-version
        run: echo "::set-output name=app-version::$(version=`grep 'version:' ./helm/Chart.yaml | cut -d ' ' -f 2` && echo `echo $version | cut -d '.' -f 1,2`.$((`echo $version | cut -d '.' -f 3`+1)))"

  build-frontend:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/hc-solutions/${{ needs.checkout.outputs.app-name }}-frontend:${{ needs.checkout.outputs.app-version }}

  

  build-backend:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    needs: [checkout]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/backend.dockerfile
          push: true
          tags: ghcr.io/hc-solutions/${{ needs.checkout.outputs.app-name }}-backend:${{ needs.checkout.outputs.app-version }}

  scan-frontend:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    needs: [build-frontend]
    steps:
      - name: Scan frontend image
        uses: Azure/container-scan@v0
        with:
          image-name: ghcr.io/hc-solutions/${{ needs.checkout.outputs.app-name }}-frontend:${{ needs.checkout.outputs.app-version }}
          severity-threshold: HIGH

  scan-backend:
    if: ${{ (github.event.review.state == 'approved') || (github.event_name == 'push') }}
    runs-on: self-hosted
    needs: [build-backend]
    steps:
      - name: Scan backend image
        uses: Azure/container-scan@v0
        with:
          image-name: ghcr.io/hc-solutions/${{ needs.checkout.outputs.app-name }}-backend:${{ needs.checkout.outputs.app-version }}
          severity-threshold: HIGH

