name: Integration

on:
  push:
    branches: ["staging"]
  pull_request_review:
    branches: ["staging"]
    types: [submitted]

jobs:
  print:
    runs-on: self-hosted
    steps:
    - name: read github variable
      run: echo ${{ github }}